language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install .
    - pip install nose
script:
    - udp-test --help
    - udp-test.py --help
    - cd test
    - nosetests
    